// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Robot;

/**
 *
 */
public class RunTurretVision extends Command {
    private static final double ALIGNMENT_RANGE_INNER = 3;
    private static final double ALIGNMENT_RANGE_OUTER = 10;

    private double[] visionResults;
    private double horizontalAngle;
    private double verticalAngle;
    private double alignmentAngle;
    private double distance;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public RunTurretVision() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.turret);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        visionResults = new double[] {0, 0};
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        // Result key:
        //  0. timestamp
        //  1. success (0/1)
        //  2. distance
        //  3. horizontal angle
        //  4. vertical angle
        //  5. alignment angle
        //  6. inner port (0/1)
        //  7. instantaneous FPS
        visionResults = SmartDashboard.getNumberArray("Vision/result", new double[] {0, 0});
        if (visionResults[1] == 0) {
            Robot.turret.status = "none";
            SmartDashboard.putString("Vision/valid_shot", Robot.turret.status);
            return;
        }

        distance = visionResults[2];
        horizontalAngle = visionResults[3];
        verticalAngle = visionResults[4];
        alignmentAngle = visionResults[5];

        Robot.turret.setHorizontalAngleRelative(horizontalAngle);
        Robot.turret.setVerticalAngle(verticalAngle);

        if (Robot.turret.atHorizontalAngle(horizontalAngle) && Robot.turret.atVerticalAngle(verticalAngle)) {
            // if (alignmentAngle < ALIGNMENT_RANGE_INNER) {
            //     SmartDashboard.putString("Vision/valid_shot", "inner");
            // } else if (alignmentAngle < ALIGNMENT_RANGE_OUTER) {
            //     SmartDashboard.putString("Vision/valid_shot", "outer");
            // } else {
            //     SmartDashboard.putString("Vision/valid_shot", "locked but none");
            // }
            Robot.turret.status = "locked";
            SmartDashboard.putString("Vision/valid_shot", Robot.turret.status);
        } else {
            Robot.turret.status = "homing";
            SmartDashboard.putString("Vision/valid_shot", Robot.turret.status);
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.turret.setHorizontalAngleAbsolute(0);
        SmartDashboard.putBoolean("Vision/error", false);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
